### ISSUE TITLE
install FILES given no DESTINATION

### ISSUE THREAD

**Issue by SilverShadowx** [intel/dynamic-application-loader-host-interface#2]
_Upon Performing this command, "cmake .;make;sudo make install;sudo systemctl enable jhi"_

CMake Error at CMakeLists.txt:274 (install):
cmake .;make;sudo make install;sudo systemctl enable jhi"_

CMake Error at CMakeLists.txt:274 (install):
  install FILES given no DESTINATION!

-- Configuring incomplete, errors occurred!
See also "/home/erictran/Downloads/dynamic-application-loader-host-interface/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
_This can be replicated by performing the command again, or individually._

**Comment by jlahav** [comment]
One possibility:

What init system do you have on this system?
The cmake file assumes systemd by default.

To use SysVinit instead of systemd run:
cmake . -DINIT_SYSTEM=SysVinit

Was this the cause?

**Comment by SilverShadowx** [comment]
Thank you jlahav, this worked well and sorry about the formatting. Everything seems to be working as intended.

**Comment by mitar** [comment]
I also had the same problem because I am trying to install it inside a Docker container, where there is no init at all. Could it just skip installing service file in that case?

**Comment by mitar** [comment]
For me the issue was that I didn't had `pkg-config` installed so `COMMAND pkg-config systemd --variable=systemdsystemunitdir OUTPUT_VARIABLE SYSTEMD_DIR` failed. Interestingly, it didn't throw and error at that time.
