### ISSUE TITLE
cmake fails on ubuntu linux with errors from install 

### ISSUE THREAD

**Issue by patanir** [intel/dynamic-application-loader-host-interface#7]
>:~/dynamic-application-loader-host-interface-master$ cmake .
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.3")
CMake Error at CMakeLists.txt:274 (install):
  install FILES given no DESTINATION!

-- Configuring incomplete, errors occurred!
See also "/home/user1/dynamic-application-loader-host-interface-master/CMakeFiles/CMakeOutput.log".

**Comment by jlahav** [comment]
What version of Ubuntu is this? Do you have systemd? If you don't, please use SysVinit flag: https://github.com/intel/dynamic-application-loader-host-interface/blob/master/readme.md#build-options

**Comment by rberg2** [comment]
Hello,
I just hit this issue on a fresh install of Ubuntu Server 16.04, to fix this you need to install the 'pkg-config' package.

**Comment by jlahav** [comment]
Thanks Richard. I'll add it to the list of dependencies.

**Comment by jlahav** [comment]
Added.
