### ISSUE TITLE
Dependencies need to include libsystemd-dev

### ISSUE THREAD

**Issue by ghost** [intel/dynamic-application-loader-host-interface#9]
Latest download produces this error on Ubuntu 16.04

home/mpdemo/dynamic-application-loader-host-interface/service/LinuxService.cpp:39:31: fatal error: systemd/sd-daemon.h: No such file or directory
compilation terminated.
CMakeFiles/jhid.dir/build.make:470: recipe for target 'CMakeFiles/jhid.dir/service/LinuxService.cpp.o' failed
make[2]: *** [CMakeFiles/jhid.dir/service/LinuxService.cpp.o] Error 1
CMakeFiles/Makefile2:252: recipe for target 'CMakeFiles/jhid.dir/all' failed
make[1]: *** [CMakeFiles/jhid.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jlahav** [comment]
You are right. Thank you for noticing. The way the service communicates with systemd (when compiling with systemd, which is the default)  has changed to require this lib.

I'll add it to the doc.

**Comment by jlahav** [comment]
Done
